export const countryToRegionMap = {
  'US': 'North America',
  'CA': 'North America',
  'MX': 'North America',
  'FR': 'Europe',
  'DE': 'Europe',
  'UK': 'Europe',
  'IT': 'Europe',
  'ES': 'Europe',
  'UG': 'Africa',
  'KE': 'Africa',
  'NG': 'Africa',
  'EG': 'Africa',
  'SG': 'Asia',
  'JP': 'Asia',
  'CN': 'Asia',
  'IN': 'Asia',
  'AU': 'Australia',
  'NZ': 'Australia',
};